### ISSUE TITLE
Limit memory usage

### ISSUE THREAD

**Issue by snadon** [imdrasil/crymagick#10]
Hi, I need a way to limit memory usage for an application.

Is there a way to configure the MAGICK_MEMORY_LIMIT?

https://www.imagemagick.org/script/resources.php#environment

**Comment by imdrasil** [comment]
you should be able to to set it globally. Is this an issue for your project?

**Comment by snadon** [comment]
I'm using this shard in a lucky framework project and whenever someone upload a photo my Heroku Dyno memory goes to the roof and rarely goes down after.

How can I set it globally?

**Comment by imdrasil** [comment]
It seems [this article](https://millarian.com/ops/imagemagick-memory-issues-on-heroku-16/) should point you to the right direction

**Comment by snadon** [comment]
Excellent thank you.
