### ISSUE TITLE
require "crymagick" causes Error: undefined constant ::Tempfile

### ISSUE THREAD

**Issue by AndreeWille** [imdrasil/crymagick#4]
When i execute a crystal file that requires "crymagick" i get the following error: 
`Error: undefined constant ::Tempfile`

I compared CryMagic V1 with CryMagick V0.1.1 and saw that in V0.1.1 the Tempfile class has been deleted. When i add a tempfile.cr file to the src folder and copy the deleted Tempfile class into tempfile.cr then the error disappears and i can convert images.

I wanted to  create a pull request for this but unfortunately specs are failing before i made any changes.

CryMagick version: 0.1.1
Crystal version: 0.35.1
OS: Ubuntu 20.04.1 LTS on Windows Subsystem for Linux V2
LLVM: 8.0.0

**Comment by imdrasil** [comment]
Apologies for such a long response. It seams master branch version doesn't have this issue. Going to fix other issues related to crystal changes in core library and release a new version
