### ISSUE TITLE
CryMagick::Image.build produces an error

### ISSUE THREAD

**Issue by lebogan** [imdrasil/crymagick#8]
This code following the example in the readme:
```
    image = CryMagick::Image.build(source) do |b|
      b.path
      b.resize size
      b.format "png"
      b.write target
    end
```
Produces this compile-time error:
```
 Error: undefined method 'build' for CryMagick::Image.class
```
This works like a charm:
``` 
    image = CryMagick::Image.open(source)
    image.path
    image.resize size
    image.format "png"
    image.write target
```
Did I miss something? Thank you for this shard.

**Comment by imdrasil** [comment]
Hehe, `.build` method wasn't even introduced)) I used to use combination of `.new` and `#combine_options` manually that's why missed this. Will fix it tomorrow
